spring:
  kafka:
    bootstrap-servers: 192.168.31.161:9092,192.168.31.162:9092,192.168.31.163:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

